version: '3'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: 
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
      - springapiconnection
  springapi:
    depends_on:
      - mysqldb
    build:
      context: .
      dockerfile: DockerFile
    restart: on-failure
    env_file: 
      - .env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - springapiconnection
volumes:
  db:
networks:
  springapiconnection: